### ISSUE TITLE
Caligraphy error

### ISSUE THREAD

**Issue by TheKnightCode** [raffitz/mawkin-sans#5]
In Chozo caligraphy. Letters still oscilate after spaces. But in this font, after a space, the next word always starts with the first letter pointing down regardless if the previous one ended with a letter pointing up or down. Fixing this I believe shouldn't be hard and doing it makes this font perfect for typing in Chozo.

**Comment by raffitz** [comment]
This has been updated, check the latest release (v0.9).

**Comment by TheKnightCode** [comment]
Was it? When I initially downloaded tha font it was still incorrect. I'll check it out. Thank you and sorry for bothering you.

**Comment by raffitz** [comment]
No, you misunderstood. This was updated *yesterday*, check the latest release *from yesterday*.

**Comment by TheKnightCode** [comment]
It appears that I really misunderstood. I only noticed the update was made the day before after I wrote the message. I've downloaded the new version, tested it and it works perfectly. It's, at least for me, the perfect font for writting in Chozo now. Thank you very much and keep up the good work!
